version: '3.8'
services:
  server:
    build: .
    ports:
      - "2023:1992"
    restart: always
   
  # client:
  #   build: ./Client
  #   ports:
  #     - "2020:1992"
  #   depends_on:
  #     - server
  #   restart: always