@base_url= http://localhost:3000

###Customer
PUT {{base_url}}/api/auth/email/1
Authorization: Bearer {{$dotenv Token}}
Content-Type: application/json


{
  "currentMail": "john.doe@example.com",
  "mail": "john.doe@example.com",
  "mailConfirmation": "john.doe@example.com"
}
###
PUT {{base_url}}/api/auth/password/1
Authorization: Bearer {{$dotenv Token}}
Content-Type: application/json

{
  "currentPassword": "password123",
  "password": "newpassword456",
  "passwordConfirmation": "newpassword456"
}
###
PUT {{base_url}}/api/auth/phone/1
Content-Type: application/json
Authorization: Bearer {{$dotenv Token}}

{
  "currentphone": "123456789",
  "phone": "password",
  "phoneConfirmation": "password"
}
###

POST {{base_url}}/api/auth/local
Content-Type: application/json

{
  "identifier": "john.doe@example.com",
  "password": "password123"
}
###
POST {{base_url}}/api/auth/local/logout
Content-Type: application/json
Authorization: Bearer {{$dotenv Token}}

###
POST {{base_url}}/api/auth/local/register
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.doe@example.com",
  "phone": "123456789",
  "password": "password123",
  "address": "4 rue moby dick",
  "role": "admin"
}
###
GET {{base_url}}/api/auth/local/user/me
Authorization: Bearer {{$dotenv Token}}