@base_url= http://localhost:3000

POST {{base_url}}/api/orderitem
Content-Type: application/json

{
  "quantity": 10,
  "price_by_unity": 1.5,
  "price_by_unity_asso": 15,
  "weight_unity": 0.6,
  "unity_symbol": "litre"
}
###
GET {{base_url}}/api/orderitem/1
Content-Type: application/json
Authorization: Bearer {{$dotenv Token}}
###
PUT {{base_url}}/api/orderitem/1
Authorization: Bearer {{$dotenv Token}}
Content-Type: application/json

{
  "quantity": 5,
  "price_by_unity": 2,
  "price_by_unity_asso": 10,
  "weight_unity": 0.5,
  "unity_symbol": "litre"
}
###
DELETE {{base_url}}/api/orderitem/1
Authorization: Bearer {{$dotenv Token}}