@base_url= http://localhost:3000

POST {{base_url}}/api/productcatalogitem
Content-Type: application/json
Authorization: Bearer {{$dotenv Token}}

{
  "name": "patate",
  "description": "pomme de terre",
  "unit_value": "kg",
  "FKcategory": "Alimentaire",
  "price_by_unity": "3",
  "price_by_unity_asso": "1.5",
  "image": "https://i0.wp.com/www.programme-malin.com/wp-content/uploads/2020/02/pommes-de-terre.jpg?fit=1920%2C1080&ssl=1"
}
###
GET {{base_url}}/api/productcatalogitem
Authorization: Bearer {{$dotenv Token}}

