@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMDUxMzA0NCwiZXhwIjoxNzEwNTE2NjQ0fQ._n0mDnRhxHiezXsmWM8C-8xOUgPxzm2N_93fVWvo0b0
@base_url= http://localhost:3000

###CATEGORIES
POST {{base_url}}/api/categories/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Electronics",
  "description": "Electronic devices and gadgets"
}
###
DELETE {{base_url}}/api/categories/
Content-Type: application/json
Authorization: Bearer {{token}}
###
DELETE {{base_url}}/api/categories/2
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{base_url}}/api/categories
###
GET {{base_url}}/api/categories/3
###
PUT {{base_url}}/api/categories/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Electronics",
  "description": "Electronic devices and gadgets"
  }

###Customer
GET {{base_url}}/api/auth
###
PUT {{base_url}}/api/auth/email/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentMail": "john.doe@example.com",
  "mail": "john.doe@example.com",
  "mailConfirmation": "john.doe@example.com"
}
###

PUT {{base_url}}/api/auth/password/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "currentPassword": "password123",
  "password": "newpassword456",
  "passwordConfirmation": "newpassword456"
}
###
PUT {{base_url}}/api/auth/phone/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentphone": "123456789",
  "phone": "password",
  "phoneConfirmation": "password"
}
###

POST {{base_url}}/api/auth/local
Content-Type: application/json

{
  "identifier": "john.doe@example.com",
  "password": "password123"
}
###
POST {{base_url}}/api/auth/local/logout
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{base_url}}/api/auth/local/register
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.doe@example.com",
  "phone": "123456789",
  "password": "password123",
  "address": "4 rue moby dick",
  "role": "admin"
}

###
GET {{base_url}}/api/auth/local/user/me
Authorization: Bearer {{token}}

###product
POST {{base_url}}/api/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Nom du produit",   
  "description": "Description du produit",
  "unit_value":"unit",
  "FKcategory": "Electronics"
}
###
GET {{base_url}}/api/product
###
GET {{base_url}}/api/product/1
###CATALOG
GET {{base_url}}/api/catalog/1
###
GET {{base_url}}/api/catalog
###
POST {{base_url}}/api/catalog
Content-Type: application/json
Authorization: Bearer {{token}}

{
"store": "Paris"
}
###
PUT {{base_url}}/api/catalog/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
"store": "Paris"
}
###ORDER
POST {{base_url}}/api/order
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "order_date": "2023-03-15",
  "status": "payed",
  "collect_schedule": "2023-03-16" //besoin d'une date de livraison reelle ? 
}
###
PUT {{base_url}}/api/order/status/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "payed"
}

